//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetBrowser.APIs.Enums {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetBrowser.APIs.Enums.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AnnoScope and all of its exposed members are part of a managed wrapper for the Component Object Model (COM) accessibility interface..
        /// </summary>
        internal static string Accessibility_EnumDescription {
            get {
                return ResourceManager.GetString("Accessibility_EnumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the settings for a build.^Defines how MSBuild loads a project.^Specifies constants that define the location in the project to insert a property.^An enumeration whose values control Toolset initialization..
        /// </summary>
        internal static string Microsoft_Build_BuildEngine_EnumDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.BuildEngine_EnumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties or other mutable state associated with a ProjectCollection project collection.^Flags for controlling the project load.^Flags for controlling the toolset initialization..
        /// </summary>
        internal static string Microsoft_Build_Evaluation_EnumDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Evaluation_EnumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags providing additional control over the build request.^Enumerated data indicating the build result of a target or a build request.^An enumerated data type that determines where projects are built.^Reasons for a node to shutdown.^Contains settings for controlling project instance creation.^The result code for a given target..
        /// </summary>
        internal static string Microsoft_Build_Execution_EnumDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Execution_EnumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the available verbosity levels of a Logger.^Specifies constants that define the importance of a build message.^Defines the lifetime of a registered task object..
        /// </summary>
        internal static string Microsoft_Build_Framework_EnumDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Framework_EnumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether the default value for a property is set at the bottom or the top of the project file.^Describes a subsequent definition for a rule with the same name..
        /// </summary>
        internal static string Microsoft_Build_Framework_XamlTypes_EnumDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Framework.XamlTypes_EnumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This enumeration provides three levels of importance for build messages.^Specifies the way that required components will be published..
        /// </summary>
        internal static string Microsoft_Build_Tasks_Deployment_Bootstrapper_EnumDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks.Deployment.Bootstrapper_EnumDescription", resourceCulture);
            }
        }
    }
}
