//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetBrowser.APIs.Enums {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Enums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Enums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetBrowser.APIs.Enums.Enums", typeof(Enums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnnoScope.
        /// </summary>
        internal static string Accessibility_EnumName {
            get {
                return ResourceManager.GetString("Accessibility_EnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildSettings^ProjectLoadSettings^PropertyPosition^ToolsetDefinitionLocations.
        /// </summary>
        internal static string Microsoft_Build_BuildEngine_EnumName {
            get {
                return ResourceManager.GetString("Microsoft.Build.BuildEngine_EnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectCollectionChangedState^ProjectLoadSettings^ToolsetDefinitionLocations.
        /// </summary>
        internal static string Microsoft_Build_Evaluation_EnumName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Evaluation_EnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildRequestDataFlags^BuildResultCode^NodeAffinity^NodeEngineShutdownReason^ProjectInstanceSettings^TargetResultCode.
        /// </summary>
        internal static string Microsoft_Build_Execution_EnumName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Execution_EnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoggerVerbosity^MessageImportance^RegisteredTaskObjectLifetime.
        /// </summary>
        internal static string Microsoft_Build_Framework_EnumName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Framework_EnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultValueSourceLocation^RuleOverrideMode.
        /// </summary>
        internal static string Microsoft_Build_Framework_XamlTypes_EnumName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Framework.XamlTypes_EnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildMessageSeverity^ComponentsLocation.
        /// </summary>
        internal static string Microsoft_Build_Tasks_Deployment_Bootstrapper_EnumName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks.Deployment.Bootstrapper_EnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyIdentity.FullNameFlags^AssemblyReferenceType^OutputMessageType^UpdateMode^UpdateUnit.
        /// </summary>
        internal static string Microsoft_Build_Tasks_Deployment_ManifestUtilities_EnumName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks.Deployment.ManifestUtilities_EnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandLineToolSwitchType^MemberVisibility.
        /// </summary>
        internal static string Microsoft_Build_Tasks_Xaml_EnumName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks.Xaml_EnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotNetFrameworkArchitecture^ExecutableType^HostObjectInitializationStatus^TargetDotNetFrameworkVersion^UpToDateCheckType^VisualStudioVersion.
        /// </summary>
        internal static string Microsoft_Build_Utilities_EnumName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Utilities_EnumName", resourceCulture);
            }
        }
    }
}
