//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetBrowser.APIs.Structs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Structs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Structs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetBrowser.APIs.Structs.Structs", typeof(Structs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __MIDL_IWinTypes_0009^_RemotableHandle.
        /// </summary>
        internal static string Accessibility_StructName {
            get {
                return ResourceManager.GetString("Accessibility_StructName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResolvedImport.
        /// </summary>
        internal static string Microsoft_Build_Evaluation_StructName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Evaluation_StructName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildEngineResult.
        /// </summary>
        internal static string Microsoft_Build_Framework_StructName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Framework_StructName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtractedClassName.
        /// </summary>
        internal static string Microsoft_Build_Tasks_StructName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks_StructName", resourceCulture);
            }
        }
    }
}
