//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetBrowser.APIs.Namespaces {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetBrowser.APIs.Namespaces.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Accessibility and all of its exposed members are part of a managed wrapper for the Component Object Model (COM) accessibility interface..
        /// </summary>
        internal static string Accessibility_NamespaceDescription {
            get {
                return ResourceManager.GetString("Accessibility_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes related to the build debugger..
        /// </summary>
        internal static string Microsoft_Activities_Build_Debugger_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Activities.Build.Debugger_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes related to build expressions..
        /// </summary>
        internal static string Microsoft_Activities_Build_Expressions_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Activities.Build.Expressions_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes related to workflow build tasks..
        /// </summary>
        internal static string Microsoft_Activities_Build_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Activities.Build_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provides classes related to build validation..
        /// </summary>
        internal static string Microsoft_Activities_Build_Validation_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Activities.Build.Validation_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace represents the MSBuild engine. For information, see MSBuild..
        /// </summary>
        internal static string Microsoft_Build_BuildEngine_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.BuildEngine_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains types that the MSBuild object model uses to construct project roots with unevaluated values. Each project root corresponds to a project or targets file. For information, see MSBuild..
        /// </summary>
        internal static string Microsoft_Build_Construction_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Construction_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains types that Visual Studio uses to convert project files from an older version of Visual Studio..
        /// </summary>
        internal static string Microsoft_Build_Conversion_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Conversion_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains type for managing the debugger..
        /// </summary>
        internal static string Microsoft_Build_Debugging_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Debugging_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains types that the MSBuild object model uses to evaluate projects. Each project is associated with one or more project roots. For information, see MSBuild..
        /// </summary>
        internal static string Microsoft_Build_Evaluation_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Evaluation_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains exception types that may be thrown during the build process..
        /// </summary>
        internal static string Microsoft_Build_Exceptions_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Exceptions_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains types that the MSBuild object model uses to build projects. For information, see MSBuild..
        /// </summary>
        internal static string Microsoft_Build_Execution_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Execution_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains the types that define how tasks and loggers interact with the MSBuild engine. For information, see MSBuild..
        /// </summary>
        internal static string Microsoft_Build_Framework_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Framework_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes used to represent XAML types parsed from files, rules, and other sources..
        /// </summary>
        internal static string Microsoft_Build_Framework_XamlTypes_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Framework.XamlTypes_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains types used for logging the progress of a build. For information, see MSBuild..
        /// </summary>
        internal static string Microsoft_Build_Logging_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Logging_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains classes used internally by MSBuild..
        /// </summary>
        internal static string Microsoft_Build_Tasks_Deployment_Bootstrapper_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks.Deployment.Bootstrapper_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains classes that MSBuild uses..
        /// </summary>
        internal static string Microsoft_Build_Tasks_Deployment_ManifestUtilities_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks.Deployment.ManifestUtilities_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains classes used internally by MSBuild..
        /// </summary>
        internal static string Microsoft_Build_Tasks_Hosting_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks.Hosting_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains the implementation of all tasks shipping with MSBuild. For information, see MSBuild..
        /// </summary>
        internal static string Microsoft_Build_Tasks_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains the implementation of all tasks shipping with MSBuild. The types in this namespace support the Windows Presentation Foundation (WPF) infrastructure and are not intended to be used directly from your code..
        /// </summary>
        internal static string Microsoft_Build_Tasks_Windows_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks.Windows_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides classes related to XAML build tasks..
        /// </summary>
        internal static string Microsoft_Build_Tasks_Xaml_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks.Xaml_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace provides helper classes that you can use to create your own MSBuild loggers and tasks. For information, see MSBuild..
        /// </summary>
        internal static string Microsoft_Build_Utilities_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Utilities_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes related to C# activities..
        /// </summary>
        internal static string Microsoft_CSharp_Activities_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.CSharp.Activities_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains classes that support compilation and code generation using the C# language..
        /// </summary>
        internal static string Microsoft_CSharp_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.CSharp_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace provides classes and interfaces that support interoperation between Dynamic Language Runtime and C#..
        /// </summary>
        internal static string Microsoft_CSharp_RuntimeBinder_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.CSharp.RuntimeBinder_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains classes that support compilation and code generation using the JScript language..
        /// </summary>
        internal static string Microsoft_JScript_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.JScript_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Microsoft.JScript.Vsa namespace contains interfaces that allow you to integrate Script for the.NET Framework script engines into JScript, and to compile and execute code at run time..
        /// </summary>
        internal static string Microsoft_JScript_Vsa_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.JScript.Vsa_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains classes, interfaces, and enumerations that are specific to the integration of the Microsoft .NET Framework common language runtime (CLR) into Microsoft SQL Server, and the SQL Server database engine process execution environment..
        /// </summary>
        internal static string Microsoft_SqlServer_Server_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.SqlServer.Server_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides classes related to Visual Basic activities..
        /// </summary>
        internal static string Microsoft_VisualBasic_Activities_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.VisualBasic.Activities_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides classes related to Visual Basic XAML integration..
        /// </summary>
        internal static string Microsoft_VisualBasic_Activities_XamlIntegration_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.VisualBasic.Activities.XamlIntegration_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains types that support the Visual Basic Application Model and provide access to application information..
        /// </summary>
        internal static string Microsoft_VisualBasic_ApplicationServices_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.VisualBasic.ApplicationServices_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains functions and objects provided use by the tools for upgrading from Visual Basic 6.0 to Visual Basic 2008..
        /// </summary>
        internal static string Microsoft_VisualBasic_Compatibility_VB6_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.VisualBasic.Compatibility.VB6_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains internal-use only types that support the Visual Basic compiler..
        /// </summary>
        internal static string Microsoft_VisualBasic_CompilerServices_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.VisualBasic.CompilerServices_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains types that support the My objects related to devices in Visual Basic..
        /// </summary>
        internal static string Microsoft_VisualBasic_Devices_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.VisualBasic.Devices_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains types that support the My file system object in Visual Basic..
        /// </summary>
        internal static string Microsoft_VisualBasic_FileIO_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.VisualBasic.FileIO_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains types that support the My logging objects in Visual Basic and provides a simple log listener that directs logging output to file..
        /// </summary>
        internal static string Microsoft_VisualBasic_Logging_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.VisualBasic.Logging_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains internal-use only types that support My in Visual Basic..
        /// </summary>
        internal static string Microsoft_VisualBasic_MyServices_Internal_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.VisualBasic.MyServices.Internal_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains types that support My in Visual Basic..
        /// </summary>
        internal static string Microsoft_VisualBasic_MyServices_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.VisualBasic.MyServices_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains types that support the Visual Basic Runtime in Visual Basic..
        /// </summary>
        internal static string Microsoft_VisualBasic_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.VisualBasic_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains classes that support compilation and code generation using the C++ language..
        /// </summary>
        internal static string Microsoft_VisualC_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.VisualC_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains the classes, interfaces, and iterators that are used to implement the generic interface to the . By using this generic interface, other .NET languages, such as C# and Visual Basic, can call code that is written using STL/CLR..
        /// </summary>
        internal static string Microsoft_VisualC_StlClr_Generic_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.VisualC.StlClr.Generic_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains the classes, interfaces, and enumerators that are used to implement the STL/CLR Library..
        /// </summary>
        internal static string Microsoft_VisualC_StlClr_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.VisualC.StlClr_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace provides two types of classes: those that handle events raised by the operating system and those that manipulate the system registry..
        /// </summary>
        internal static string Microsoft_Win32_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Win32_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The namespace contains classes that are abstract derivations of safe handle classes that provide common functionality supporting file and operating system handles..
        /// </summary>
        internal static string Microsoft_Win32_SafeHandles_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Win32.SafeHandles_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains interfaces for preview commands in a Microsoft Ribbon for WPF control..
        /// </summary>
        internal static string Microsoft_Windows_Input_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Windows.Input_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides exposure to the set of themes defined by Windows Presentation Foundation. In WPF, a theme is a set of resources, defined at the system level, which provide the default appearance for controls and other visual elements of an application. WPF themes are created using styles and include Luna, Aero, Royale, and Classic. Only the client area of a WPF application uses these themes; the appearance of the window border and buttons that form the window chrome is controlled by the Win32 theme service..
        /// </summary>
        internal static string Microsoft_Windows_Themes_NamespaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Windows.Themes_NamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
    }
}
