//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetBrowser.APIs.Namespaces {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Namespaces {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Namespaces() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetBrowser.APIs.Namespaces.Namespaces", typeof(Namespaces).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        internal static string Accessibility_Namespaces {
            get {
                return ResourceManager.GetString("Accessibility_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Activities.Build,Microsoft.Activities.Build.Debugger,Microsoft.Activities.Build.Expressions,Microsoft.Activities.Build.Validation.
        /// </summary>
        internal static string Microsoft_Activities_Namespaces {
            get {
                return ResourceManager.GetString("Microsoft.Activities_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Build.BuildEngine,Microsoft.Build.Construction,Microsoft.Build.Conversion,Microsoft.Build.Debugging,Microsoft.Build.Evaluation,Microsoft.Build.Exceptions,Microsoft.Build.Execution,Microsoft.Build.Framework,Microsoft.Build.Framework.XamlTypes,Microsoft.Build.Logging,Microsoft.Build.Tasks,Microsoft.Build.Tasks.Deployment.Bootstrapper,Microsoft.Build.Tasks.Deployment.ManifestUtilities,Microsoft.Build.Tasks.Hosting,Microsoft.Build.Tasks.Windows,Microsoft.Build.Tasks.Xaml,Microsoft.Build.Utilities.
        /// </summary>
        internal static string Microsoft_Build_Namespaces {
            get {
                return ResourceManager.GetString("Microsoft.Build_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.CSharp,Microsoft.CSharp.Activities,Microsoft.CSharp.RuntimeBinder.
        /// </summary>
        internal static string Microsoft_CSharp_Namespaces {
            get {
                return ResourceManager.GetString("Microsoft.CSharp_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.JScript,Microsoft.JScript.Vsa.
        /// </summary>
        internal static string Microsoft_JScript_Namespaces {
            get {
                return ResourceManager.GetString("Microsoft.JScript_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.SqlServer.Server.
        /// </summary>
        internal static string Microsoft_SqlServer_Namespaces {
            get {
                return ResourceManager.GetString("Microsoft.SqlServer_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.VisualBasic,Microsoft.VisualBasic.Activities,Microsoft.VisualBasic.Activities.XamlIntegration,Microsoft.VisualBasic.ApplicationServices,Microsoft.VisualBasic.Compatibility.VB6,Microsoft.VisualBasic.CompilerServices,Microsoft.VisualBasic.Devices,Microsoft.VisualBasic.FileIO,Microsoft.VisualBasic.Logging,Microsoft.VisualBasic.MyServices,Microsoft.VisualBasic.MyServices.Internal.
        /// </summary>
        internal static string Microsoft_VisualBasic_Namespaces {
            get {
                return ResourceManager.GetString("Microsoft.VisualBasic_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.VisualC,Microsoft.VisualC.StlClr,Microsoft.VisualC.StlClr.Generic.
        /// </summary>
        internal static string Microsoft_VisualC_Namespaces {
            get {
                return ResourceManager.GetString("Microsoft.VisualC_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Win32,Microsoft.Win32.SafeHandles.
        /// </summary>
        internal static string Microsoft_Win32_Namespaces {
            get {
                return ResourceManager.GetString("Microsoft.Win32_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Windows.Input,Microsoft.Windows.Themes.
        /// </summary>
        internal static string Microsoft_Windows_Namespaces {
            get {
                return ResourceManager.GetString("Microsoft.Windows_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Activities.Core.Presentation,System.Activities.Core.Presentation.Factories,System.Activities.Core.Presentation.Themes.
        /// </summary>
        internal static string System_Activities_Core_Namespaces {
            get {
                return ResourceManager.GetString("System.Activities.Core_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Activities.Debugger,System.Activities.Debugger.Symbol.
        /// </summary>
        internal static string System_Activities_Debugger_Namespaces {
            get {
                return ResourceManager.GetString("System.Activities.Debugger_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Activities.DurableInstancing.
        /// </summary>
        internal static string System_Activities_DurableInstancing_Namespaces {
            get {
                return ResourceManager.GetString("System.Activities.DurableInstancing_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Activities.DynamicUpdate.
        /// </summary>
        internal static string System_Activities_DynamicUpdate_Namespaces {
            get {
                return ResourceManager.GetString("System.Activities.DynamicUpdate_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Activities.ExpressionParser.
        /// </summary>
        internal static string System_Activities_ExpressionParser_Namespaces {
            get {
                return ResourceManager.GetString("System.Activities.ExpressionParser_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Activities.Expressions.
        /// </summary>
        internal static string System_Activities_Expressions_Namespaces {
            get {
                return ResourceManager.GetString("System.Activities.Expressions_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Activities.Hosting.
        /// </summary>
        internal static string System_Activities_Hosting_Namespaces {
            get {
                return ResourceManager.GetString("System.Activities.Hosting_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Activities.
        /// </summary>
        internal static string System_Activities_Namespaces {
            get {
                return ResourceManager.GetString("System.Activities_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Activities.Persistence.
        /// </summary>
        internal static string System_Activities_Persistence_Namespaces {
            get {
                return ResourceManager.GetString("System.Activities.Persistence_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Activities.Presentation,System.Activities.Presentation.Annotations,System.Activities.Presentation.Converters,System.Activities.Presentation.Debug,System.Activities.Presentation.Expressions,System.Activities.Presentation.Hosting,System.Activities.Presentation.Metadata,System.Activities.Presentation.Model,System.Activities.Presentation.PropertyEditing,System.Activities.Presentation.Services,System.Activities.Presentation.Sqm,System.Activities.Presentation.Toolbox,System.Activities.Presentation.Validati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Activities_Presentation_Namespaces {
            get {
                return ResourceManager.GetString("System.Activities.Presentation_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Activities.Statements,System.Activities.Statements.Tracking.
        /// </summary>
        internal static string System_Activities_Statements_Namespaces {
            get {
                return ResourceManager.GetString("System.Activities.Statements_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Activities.Tracking.
        /// </summary>
        internal static string System_Activities_Tracking_Namespaces {
            get {
                return ResourceManager.GetString("System.Activities.Tracking_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Activities.Validation.
        /// </summary>
        internal static string System_Activities_Validation_Namespaces {
            get {
                return ResourceManager.GetString("System.Activities.Validation_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Activities.XamlIntegration.
        /// </summary>
        internal static string System_Activities_XamlIntegration_Namespaces {
            get {
                return ResourceManager.GetString("System.Activities.XamlIntegration_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.AddIn,System.AddIn.Contract,System.AddIn.Contract.Automation,System.AddIn.Contract.Collections,System.AddIn.Hosting,System.AddIn.Pipeline.
        /// </summary>
        internal static string System_AddIn_Namespaces {
            get {
                return ResourceManager.GetString("System.AddIn_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.CodeDom,System.CodeDom.Compiler.
        /// </summary>
        internal static string System_CodeDom_Namespaces {
            get {
                return ResourceManager.GetString("System.CodeDom_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections,System.Collections.Concurrent,System.Collections.Generic,System.Collections.ObjectModel,System.Collections.Specialized.
        /// </summary>
        internal static string System_Collections_Namespaces {
            get {
                return ResourceManager.GetString("System.Collections_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.ComponentModel.Composition,System.ComponentModel.Composition.Hosting,System.ComponentModel.Composition.Primitives,System.ComponentModel.Composition.ReflectionModel,System.ComponentModel.Composition.Registration.
        /// </summary>
        internal static string System_ComponentModel_Composition_Namespaces {
            get {
                return ResourceManager.GetString("System.ComponentModel.Composition_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.ComponentModel.DataAnnotations,System.ComponentModel.DataAnnotations.Schema.
        /// </summary>
        internal static string System_ComponentModel_DataAnnotations_Namespaces {
            get {
                return ResourceManager.GetString("System.ComponentModel.DataAnnotations_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.ComponentModel.Design,System.ComponentModel.Design.Data,System.ComponentModel.Design.Serialization.
        /// </summary>
        internal static string System_ComponentModel_Design_Namespaces {
            get {
                return ResourceManager.GetString("System.ComponentModel.Design_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.ComponentModel.
        /// </summary>
        internal static string System_ComponentModel_Namespaces {
            get {
                return ResourceManager.GetString("System.ComponentModel_Namespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string System_Namespaces {
            get {
                return ResourceManager.GetString("System_Namespaces", resourceCulture);
            }
        }
    }
}
