//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetBrowser.APIs.Delegates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Delegates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Delegates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetBrowser.APIs.Delegates.Delegates", typeof(Delegates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorResetter^ColorSetter^WriteHandler.
        /// </summary>
        internal static string Microsoft_Build_BuildEngine_DelegateName {
            get {
                return ResourceManager.GetString("Microsoft.Build.BuildEngine_DelegateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectCollection.ProjectAddedEventHandler.
        /// </summary>
        internal static string Microsoft_Build_Evaluation_DelegateName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Evaluation_DelegateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildSubmissionCompleteCallback.
        /// </summary>
        internal static string Microsoft_Build_Execution_DelegateName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Execution_DelegateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnyEventHandler^BuildErrorEventHandler^BuildFinishedEventHandler^BuildMessageEventHandler^BuildStartedEventHandler^BuildStatusEventHandler^BuildWarningEventHandler^CustomBuildEventHandler^ProjectFinishedEventHandler^ProjectStartedEventHandler^TargetFinishedEventHandler^TargetStartedEventHandler^TaskFinishedEventHandler^TaskStartedEventHandler.
        /// </summary>
        internal static string Microsoft_Build_Framework_DelegateName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Framework_DelegateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorResetter^ColorSetter^WriteHandler.
        /// </summary>
        internal static string Microsoft_Build_Logging_DelegateName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Logging_DelegateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DependencyFilter.
        /// </summary>
        internal static string Microsoft_Build_Utilities_DelegateName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Utilities_DelegateName", resourceCulture);
            }
        }
    }
}
