//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetBrowser.APIs.Delegates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetBrowser.APIs.Delegates.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the type of delegate used to reset the console color.^Defines the type of delegate used to set the console color.^Represents the method that writes strings to a certain location, such as the console window or a window in an integrated development environment..
        /// </summary>
        internal static string Microsoft_Build_BuildEngine_DelegateDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.BuildEngine_DelegateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler to receive which project got added to the project collection..
        /// </summary>
        internal static string Microsoft_Build_Evaluation_DelegateDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Evaluation_DelegateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A callback function that receives notification when a build completes..
        /// </summary>
        internal static string Microsoft_Build_Execution_DelegateDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Execution_DelegateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents the method that will handle the AnyEventRaised event of a build.^Represents the method that will handle the ErrorRaised event of a build.^Represents the method that will handle the BuildFinished event of a build.^Represents the method that will handle the MessageRaised event of a build.^Represents the method that will handle the BuildStarted event of a build.^Represents the method that will handle the StatusEventRaised event of a build.^Represents the method that will handle the WarningRaised eve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Build_Framework_DelegateDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Framework_DelegateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of delegate used to reset console color.^Type of delegate used to set console color.^Delegate used for writing a string to some location like the console window or the IDE build window..
        /// </summary>
        internal static string Microsoft_Build_Logging_DelegateDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Logging_DelegateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency filter delegate. Used during TLog saves in order for tasks to selectively remove dependencies from the written graph..
        /// </summary>
        internal static string Microsoft_Build_Utilities_DelegateDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Utilities_DelegateDescription", resourceCulture);
            }
        }
    }
}
