//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetBrowser.APIs.Interfaces {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetBrowser.APIs.Interfaces.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CAccPropServices and all of its exposed members are part of a managed wrapper for the Component Object Model (COM) IAccPropServices interface.^The IAccessible interface and all of its exposed members are part of a managed wrapper for the Component Object Model (COM) IAccessible interface.^The IAccessibleHandler and all of its exposed members are part of a managed wrapper for the Component Object Model (COM) IAccessibleHandler interface.^The IAccIdentity and all of its exposed members are part of a manag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Accessibility_InterfaceDescription {
            get {
                return ResourceManager.GetString("Accessibility_InterfaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An interface representing the results for a specific target..
        /// </summary>
        internal static string Microsoft_Build_Execution_InterfaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Execution_InterfaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides a way for task authors to use a subset of the functionality of the MSBuild engine.^Provides a way for task authors to use a subset of the functionality of the MSBuild engine.^This interface extends IBuildEngine to provide a method allowing building project files in parallel.^This interface extends IBuildEngine to provide a mechanism allowing tasks to share data between task invocations.^Interface for tasks which can be cancelled.^Forwards build events to other loggers.^Defines the events raised by  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Build_Framework_InterfaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Framework_InterfaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines an interface that all root classes from project schema XAML files must implement..
        /// </summary>
        internal static string Microsoft_Build_Framework_XamlTypes_InterfaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Framework.XamlTypes_InterfaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposes functionality that you must have to create a bootstrapper.^Represents messages that occur during the BootstrapperBuilder build operation.^Represents the results of the BootstrapperBuilder build operation.^Defines the settings for the bootstrapper build operation.^Represents a product that the BootstrapperBuilder finds in the Path property.^Represents a buildable version of a Product.^Contains a collection of ProductBuilder objects.^Represents a collection of Product objects..
        /// </summary>
        internal static string Microsoft_Build_Tasks_Deployment_Bootstrapper_InterfaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks.Deployment.Bootstrapper_InterfaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides a substitute for ITypeInfo by modifying the definitions of GetRefTypeOfImplType(Int32, IntPtr) and GetRefTypeInfo(IntPtr, IFixedTypeInfo)..
        /// </summary>
        internal static string Microsoft_Build_Tasks_InterfaceDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks_InterfaceDescription", resourceCulture);
            }
        }
    }
}
