//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetBrowser.APIs.Interfaces {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Interfaces {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Interfaces() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetBrowser.APIs.Interfaces.Interfaces", typeof(Interfaces).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAccPropServices^IAccessible^IAccessibleHandler^IAccIdentity^IAccPropServer^IAccPropServices.
        /// </summary>
        internal static string Accessibility_InterfaceName {
            get {
                return ResourceManager.GetString("Accessibility_InterfaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITargetResult.
        /// </summary>
        internal static string Microsoft_Build_Execution_InterfaceName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Execution_InterfaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBuildEngine^IBuildEngine2^IBuildEngine3^IBuildEngine4^ICancelableTask^IEventRedirector^IEventSource^IForwardingLogger^IGeneratedTask^ILogger^INodeLogger^ITask^ITaskFactory^ITaskFactory2^ITaskHost^ITaskItem^ITaskItem2.
        /// </summary>
        internal static string Microsoft_Build_Framework_InterfaceName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Framework_InterfaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IProjectSchemaNode.
        /// </summary>
        internal static string Microsoft_Build_Framework_XamlTypes_InterfaceName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Framework.XamlTypes_InterfaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBootstrapperBuilder^IBuildMessage^IBuildResults^IBuildSettings^IProduct^IProductBuilder^IProductBuilderCollection^IProductCollection.
        /// </summary>
        internal static string Microsoft_Build_Tasks_Deployment_Bootstrapper_InterfaceName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks.Deployment.Bootstrapper_InterfaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFixedTypeInfo.
        /// </summary>
        internal static string Microsoft_Build_Tasks_InterfaceName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks_InterfaceName", resourceCulture);
            }
        }
    }
}
