//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetBrowser.APIs.Classes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Classes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Classes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetBrowser.APIs.Classes.Classes", typeof(Classes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAccPropServicesClass.
        /// </summary>
        internal static string Accessibility_ClassName {
            get {
                return ResourceManager.GetString("Accessibility_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkflowBuildMessageTask.
        /// </summary>
        internal static string Microsoft_Activities_Build_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Activities.Build_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebugBuildExtension.
        /// </summary>
        internal static string Microsoft_Activities_Build_Debugger_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Activities.Build.Debugger_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpressionsBuildExtension.
        /// </summary>
        internal static string Microsoft_Activities_Build_Expressions_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Activities.Build.Expressions_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeferredValidationTask^ReportDeferredValidationErrorsTask.
        /// </summary>
        internal static string Microsoft_Activities_Build_Validation_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Activities.Build.Validation_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildItem^BuildItemGroup^BuildItemGroupCollection^BuildProperty^BuildPropertyGroup^BuildPropertyGroupCollection^BuildTask^ConfigurableForwardingLogger^ConsoleLogger^DistributedFileLogger^Engine^FileLogger^Import^ImportCollection^InternalLoggerException^InvalidProjectFileException^InvalidToolsetDefinitionException^LocalNode^LoggerDescription^Project^RemoteErrorException^SolutionWrapperProject^Target^TargetCollection^Toolset^ToolsetCollection^UsingTask^UsingTaskCollection^Utilities.
        /// </summary>
        internal static string Microsoft_Build_BuildEngine_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Build.BuildEngine_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElementLocation^ProjectChooseElement^ProjectElement^ProjectElementContainer^ProjectExtensionsElement^ProjectImportElement^ProjectImportGroupElement^ProjectItemDefinitionElement^ProjectItemDefinitionGroupElement^ProjectItemElement^ProjectItemGroupElement^ProjectMetadataElement^ProjectOnErrorElement^ProjectOtherwiseElement^ProjectOutputElement^ProjectPropertyElement^ProjectPropertyGroupElement^ProjectRootElement^ProjectTargetElement^ProjectTaskElement^ProjectUsingTaskBodyElement^ProjectUsingTaskElement^Projec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Build_Construction_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Construction_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectFileConverter.
        /// </summary>
        internal static string Microsoft_Build_Conversion_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Conversion_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebuggerManager^DebuggerManager.IslandThread.
        /// </summary>
        internal static string Microsoft_Build_Debugging_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Debugging_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project^ProjectChangedEventArgs^ProjectCollection^ProjectCollection.ProjectAddedToProjectCollectionEventArgs^ProjectCollectionChangedEventArgs^ProjectItem^ProjectItemDefinition^ProjectMetadata^ProjectProperty^ProjectXmlChangedEventArgs^SubToolset^Toolset.
        /// </summary>
        internal static string Microsoft_Build_Evaluation_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Evaluation_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildAbortedException^InternalLoggerException^InvalidProjectFileException^InvalidToolsetDefinitionException.
        /// </summary>
        internal static string Microsoft_Build_Exceptions_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Exceptions_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildManager^BuildParameters^BuildRequestData^BuildResult^BuildSubmission^HostServices^OutOfProcNode^ProjectInstance^ProjectItemDefinitionInstance^ProjectItemGroupTaskInstance^ProjectItemGroupTaskItemInstance^ProjectItemGroupTaskMetadataInstance^ProjectItemInstance^ProjectMetadataInstance^ProjectOnErrorInstance^ProjectPropertyGroupTaskInstance^ProjectPropertyGroupTaskPropertyInstance^ProjectPropertyInstance^ProjectTargetInstance^ProjectTargetInstanceChild^ProjectTaskInstance^ProjectTaskInstanceChild^Project [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Build_Execution_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Execution_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuildErrorEventArgs^BuildEventArgs^BuildEventContext^BuildFinishedEventArgs^BuildMessageEventArgs^BuildStartedEventArgs^BuildStatusEventArgs^BuildWarningEventArgs^CriticalBuildMessageEventArgs^CustomBuildEventArgs^ExternalProjectFinishedEventArgs^ExternalProjectStartedEventArgs^LazyFormattedBuildEventArgs^LoadInSeparateAppDomainAttribute^LoggerException^OutputAttribute^ProjectFinishedEventArgs^ProjectStartedEventArgs^RequiredAttribute^RequiredRuntimeAttribute^RunInMTAAttribute^RunInSTAAttribute^TargetFinish [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Build_Framework_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Framework_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument^BaseProperty^BoolProperty^Category^CategorySchema^ContentType^DataSource^DynamicEnumProperty^EnumProperty^EnumValue^FileExtension^IntProperty^ItemType^NameValuePair^ProjectSchemaDefinitions^Rule^RuleBag^RuleSchema^StringListProperty^StringProperty^ValueEditor.
        /// </summary>
        internal static string Microsoft_Build_Framework_XamlTypes_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Framework.XamlTypes_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigurableForwardingLogger^ConsoleLogger^DistributedFileLogger^FileLogger^ForwardingLoggerRecord^LoggerDescription.
        /// </summary>
        internal static string Microsoft_Build_Logging_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Logging_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AL^AppDomainIsolatedTaskExtension^AspNetCompiler^AssignCulture^AssignProjectConfiguration^AssignTargetPath^CallTarget^CodeTaskFactory^CombinePath^CommandLineBuilderExtension^ConvertToAbsolutePath^Copy^CreateCSharpManifestResourceName^CreateItem^CreateManifestResourceName^CreateProperty^CreateVisualBasicManifestResourceName^Csc^Delete^Error^Exec^FindAppConfigFile^FindInList^FindUnderPath^FormatUrl^FormatVersion^GenerateApplicationManifest^GenerateBootstrapper^GenerateDeploymentManifest^GenerateManifestBase^G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Build_Tasks_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BootstrapperBuilder^BuildMessage^BuildResults^BuildSettings^Product^ProductBuilder^ProductBuilderCollection^ProductCollection.
        /// </summary>
        internal static string Microsoft_Build_Tasks_Deployment_Bootstrapper_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks.Deployment.Bootstrapper_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationIdentity^ApplicationManifest^AssemblyIdentity^AssemblyManifest^AssemblyReference^AssemblyReferenceCollection^BaseReference^ComClass^CompatibleFramework^CompatibleFrameworkCollection^DeployManifest^FileAssociation^FileAssociationCollection^FileReference^FileReferenceCollection^Manifest^ManifestReader^ManifestWriter^OutputMessage^OutputMessageCollection^ProxyStub^SecurityUtilities^TrustInfo^TypeLib^WindowClass.
        /// </summary>
        internal static string Microsoft_Build_Tasks_Deployment_ManifestUtilities_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks.Deployment.ManifestUtilities_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileClassifier^GenerateTemporaryTargetAssembly^GetWinFXPath^MarkupCompilePass1^MarkupCompilePass2^MergeLocalizationDirectives^ResourcesGenerator^UidManager^UpdateManifestForBrowserApplication.
        /// </summary>
        internal static string Microsoft_Build_Tasks_Windows_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks.Windows_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttributeData^AttributeParameterData^BuildExtensionContext^ClassData^CommandLineArgumentRelation^CommandLineGenerator^CommandLineToolSwitch^CompilationPass2Task^GenerateTemporaryAssemblyTask^NamedObject^PartialClassGenerationTask^PropertyData^PropertyRelation^XamlBuildTypeGenerationExtensionContext^XamlBuildTypeInspectionExtensionContext^XamlDataDrivenToolTask.
        /// </summary>
        internal static string Microsoft_Build_Tasks_Xaml_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Tasks.Xaml_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppDomainIsolatedTask^AssemblyFoldersExInfo^CanonicalTrackedInputFiles^CanonicalTrackedOutputFiles^CommandLineBuilder^FileTracker^FlatTrackingData^Logger^MuxLogger^ProcessorArchitecture^TargetPlatformSDK^Task^TaskItem^TaskLoggingHelper^ToolLocationHelper^ToolTask^TrackedDependencies.
        /// </summary>
        internal static string Microsoft_Build_Utilities_ClassName {
            get {
                return ResourceManager.GetString("Microsoft.Build.Utilities_ClassName", resourceCulture);
            }
        }
    }
}
