//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetBrowser.APIs.Classes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetBrowser.APIs.Classes.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CAccPropServicesClass and all of its exposed members are part of a managed wrapper for the Component Object Model (COM) IAccPropServices interface..
        /// </summary>
        internal static string Accessibility_ClassDescription {
            get {
                return ResourceManager.GetString("Accessibility_ClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies information about the workflow build message task..
        /// </summary>
        internal static string Microsoft_Activities_Build_ClassDescription {
            get {
                return ResourceManager.GetString("Microsoft.Activities.Build_ClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Extension for Workflow debugger support..
        /// </summary>
        internal static string Microsoft_Activities_Build_Debugger_ClassDescription {
            get {
                return ResourceManager.GetString("Microsoft.Activities.Build.Debugger_ClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies information about the expressions build extension..
        /// </summary>
        internal static string Microsoft_Activities_Build_Expressions_ClassDescription {
            get {
                return ResourceManager.GetString("Microsoft.Activities.Build.Expressions_ClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents a task for deferring validation.^Represents a task that reports any deferred validation errors..
        /// </summary>
        internal static string Microsoft_Activities_Build_Validation_ClassDescription {
            get {
                return ResourceManager.GetString("Microsoft.Activities.Build.Validation_ClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents a single item in an MSBuild project.^Represents a collection of BuildItem objects.^Represents a collection of BuildItemGroup objects.^Represents a single property in an MSBuild project.^Represents a collection of BuildProperty objects.^Represents a collection of BuildPropertyGroup objects.^Represents a Task element in a project.^Represents the ConfigurableForwardingLogger, a pre-fabricated forwarding logger to be used when building projects on a multi-proc or multi-core system. For more informati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Build_BuildEngine_ClassDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.BuildEngine_ClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of an XML node in a file.
        ///
        ///Any editing of the project XML through the MSBuild API&apos;s will invalidate locations in that XML until the XML is reloaded.^Represents the Choose Element (MSBuild) in an MSBuild project.^Abstract base class for MSBuild construction object model elements.^Provides an abstract container class for project elements.^Represents the ProjectExtensions Element (MSBuild) in an MSBuild project. Project extensions can contain arbitrary XML content.^Represents an Import Element ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Build_Construction_ClassDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Construction_ClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converts a Visual Studio project file to the Visual Studio 2010 project file format..
        /// </summary>
        internal static string Microsoft_Build_Conversion_ClassDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Conversion_ClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager for supporting debugging a state machine.^Executes the islands on a dedicated worker thread. The worker thread&apos;s physical callstack then maps to the interpreter&apos;s virtual callstack..
        /// </summary>
        internal static string Microsoft_Build_Debugging_ClassDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Debugging_ClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents a project with design time semantics. This class can load project files, edit items and properties and build projects.^Event arguments for the ProjectCollectionChanged event.^Encapsulates a set of related projects, their toolsets, a default set of global properties, and the loggers that should be used to build them. A global version of this class acts as the default project collection.^Provides information about what project just got added to the ProjectCollection project collection.^Event argume [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Build_Evaluation_ClassDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Evaluation_ClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception representing the case where the build was aborted by request, as opposed to being unceremoniously shut down due to another kind of error exception.^This exception is used to wrap an unhandled exception from a logger. This exception aborts the build, and it can only be thrown by the MSBuild engine.^This exception is thrown whenever there is a problem with the user&apos;s XML project file. The problem might be semantic or syntactical. The latter would be of a type typically caught by XSD validation (i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Build_Exceptions_ClassDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Exceptions_ClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This class is the public entry point for executing builds.^This class represents all of the settings which must be specified to start a build.^Encapsulates all of the data needed to submit a build request.^Represents the current result set for all of the targets that have produced results for a particular configuration.^Represents a build request that has been submitted to the build manager for processing. The methods of this class may be used to execute synchronous or asynchronous build requests and to pro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Build_Execution_ClassDescription {
            get {
                return ResourceManager.GetString("Microsoft.Build.Execution_ClassDescription", resourceCulture);
            }
        }
    }
}
